version: "2"
services:
  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - ./:/home/node/app
    # expose:
      # - "3000"
    ports:
      - "3000:3000"
    command: [sh, -c, "npm build && npm start"]